# Generated by Django 2.0.4 on 2018-04-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
